export const allSymptoms = [
  // General
  "abdominal pain","abnormal bleeding","anorexia","weight loss",
  "weight gain","cachexia","chills","fever","fatigue","malaise","asthenia",
  "hypothermia","jaundice","sweating","swelling","lymphadenopathy",
  "dehydration","night sweats","flushing","hot flashes",
  // Cardiovascular
  "chest pain","angina","palpitations","arrhythmia","tachycardia",
  "bradycardia","claudication","cyanosis","edema","leg swelling",
  "fainting","syncope","rapid heartbeat",
  // Respiratory
  "cough","hemoptysis","dyspnea","tachypnea","bradypnea","orthopnea",
  "platypnea","trepopnea","wheezing","snoring",
  // Gastrointestinal
  "nausea","vomiting","hematemesis","diarrhea","constipation",
  "dyspepsia","heartburn","flatulence","bloating","belching",
  "melena","hematochezia","dysphagia","odynophagia","hiccups",
  "abdominal distension",
  // Neurological
  "headache","vertigo","dizziness","seizures","confusion","amnesia",
  "aphasia","dysarthria","ataxia","paresthesia","paresis",
  "tremor","tics","myoclonus","fasciculations","cataplexy",
  "hallucinations","insomnia","somnolence","neck stiffness",
  "loss of consciousness","paralysis","prosopagnosia",
  "acalculia","agnosia","alexia","anomia","apraxia","dystonia",
  "blepharospasm","ballismus","chorea","akathisia","akinesia","bradykinesia",
  // Musculoskeletal
  "joint pain","arthralgia","muscle weakness","muscle cramps",
  "back pain","neck pain","sciatica",
  // Dermatological
  "rash","urticaria","pruritus","ecchymosis","petechiae",
  "purpura","blisters","hives","alopecia","hypertrichosis",
  "nail changes","skin lesions","urticaria",
  // ENT (Ear, Nose, Throat)
  "hearing loss","tinnitus","otalgia","otorrhea","epistaxis",
  "nasal discharge","sore throat","halitosis","trismus",
  // Ocular
  "blurred vision","double vision","amaurosis","nystagmus",
  "conjunctival icterus","red eyes","eye pain",
  // Urological / Genitourinary
  "dysuria","hematuria","hematospermia","polyuria","oliguria",
  "anuria","urinary frequency","urinary retention","incontinence",
  "painful intercourse","vaginal bleeding",
  // Reproductive
  "amenorrhea","menstrual irregularities","infertility","nipple discharge",
  "breast lumps","erectile dysfunction",
  // Endocrine / Metabolic
  "excessive thirst","excessive hunger","hair loss","hot flashes",
  "cold intolerance","heat intolerance",
  // Psychiatric / Behavioral
  "anxiety","depression","mania","phobia","panic attacks",
  "apathy","euphoria","irritability","delusions","paranoid ideation",
  "suicidal ideation","hallucinations","confabulation","mood swings",
  // Hematologic / Immune
  "easy bruising","bleeding gums","petechiae","purpura","lymphadenopathy",
  "recurrent infections",
  // Cardiovascular‐related skin
  "clubbing","cyanosis","skin discoloration","cold extremities",
  // Oral / Dental
  "toothache","mouth ulcers","angular cheilitis","halitosis",
  // Systemic / Miscellaneous
  "hair loss","cold sweat","night sweats","weight changes",
  "abnormal liver enzymes (lab finding)",
  "abdominal mass","deformity","discharge (general)",
  "anxiety","brain fog","memory loss","restlessness",
  "rash","ulcers","skin ulcers","frostbite","chilblains",
  "steatorrhea","hemorrhage","hematoma","anosmia","ageusia",
  "acid reflux","heartburn","aspiration",
  "acid and chemical burns","bites and stings","animal bites",
  "blister","cuts","grazes","bottom shuffling (children)",
  "furuncle","boil","impetigo","cellulitis","lymphangitis",
  "foot pain","hip pain","knee pain","shoulder pain","elbow pain",
  "ankle pain","calf pain","heel pain","pelvic pain",
  "phalangeal pain","metatarsalgia","arthritis",
  "osteoporosis-related fractures pain",
  "arthralgia","joint swelling","joint redness",
  "abnormal carotid pulse","bruits","absent pulses",
  "bruits",
  "respiratory sounds (wheezes, crepitations)",
  "mouth breathing","snoring",
  "ascites","anasarca","hydrops fetalis",
  "anemia (lab finding symptom)",
  "acid breath (acetone)",
  "foetor","alcoholic breath","alcohol misuse signs",
  "edema (anasarca)",
  "hypoxia signs","hypocapnia","hypercapnia","hyperventilation",
  "apnea","hypopnea",
  "hypoxia","anoxia","dyspnea",
  "head droop","facial droop","ptosis","miosis","anhidrosis",
  "ptosis","Horner’s syndrome signs",
  "Kocher’s sign","Dunphy’s sign","Blumberg’s sign",
  "Massouh’s sign","Obturator sign",
  "Aure-Rozanova’s sign","Bartomier-Michelson’s sign",
  "Hamburger sign","Charcot’s triad","Reynold’s pentad",
  "palmar erythema","spider angioma","caput medusae",
  "proximal muscle weakness","distal muscle weakness",
  "flapping tremor (asterixis)",
  "blepharospasm","opisthotonus",
  "Raynaud phenomenon",
  "vascular headache","cluster headache","tension headache",
  "migraine aura","photophobia","phonophobia",
  "resting tremor","essential tremor","intention tremor",
  "sensitivity to cold","sensitivity to heat",
  "ulcers","mouth ulcers","peptic ulcers",
  "dysuria","strangury","urethral discharge",
  "postural dizziness (syncope)",
  "vasovagal syncope",
  "orthostatic hypotension (sign by symptom)",
  "Raynaud phenomenon",
  "Raynaud’s syndrome",
  "ankylosing spondylitis signs","psoriasis lesions",
  "psoriatic arthritis stiffness","enthesitis",
  "abnormal liver sounds (hepatomegaly percussion)",
  "palpable mass","lymph node enlargement",
  "node tenderness","skin nodules",
  "joint deformity",
  "charcot joint","neuropathic ulcer",
  "osmophobia",
  "cephalgia",
  "phalangeal clubbing",
  "stiff neck","Brudzinski sign","Kernig sign",
  "opisthotonus","nuchal rigidity"
];
